- hosts: all
  gather_facts: true
  become: true

  vars:
    network_name: app-network

    db_container_name: database
    db_image: fanto974/tp-devops-database:latest
    db_name: db
    db_user: usr
    db_password: pwd

    app_container_name: simple-api
    app_image: fanto974/tp-devops-simple-api:latest

    front_container_name: front
    front_image: tonuser/tp-devops-front:latest    

    proxy_container_name: httpd
    proxy_image: fanto974/tp-devops-http-server:latest

  roles:
    - docker
    - create_network
    - launch_database
    - launch_app
    - launch_front
    - launch_proxy
